# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PhyloTree
                                 A QGIS plugin
 Create, draw and link a phylogenetic tree to vector features
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-05-08
        copyright            : (C) 2020 by Isaac Stead
        email                : isaac.stead@protonmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Isaac Stead'
__date__ = '2020-05-08'
__copyright__ = '(C) 2020 by Isaac Stead'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PhyloTree class from file PhyloTree.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .phylo_tree import PhyloTreePlugin
    return PhyloTreePlugin()
